### ISSUE TITLE
Method not found: gateway_protocol.Gateway/DeployProcess when deploying BPMNs

### ISSUE THREAD

**Issue by SubhamPramanik** [jwulf/zbctl#10]
Hi,

We're running Zeebe v0.25.1 on K8s using Helm. I've port forwarded the zeebe-gateway:26500 to localhost and I'm trying to deploy BPMNs. 

When running status:
```
zbctl status --insecure
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 0.25.1
Brokers:
  Broker 0 - zeebe-zeebe-0.zeebe-zeebe.default.svc.cluster.local:26501
    Version: 0.25.1
    Partition 1 : Leader, Healthy
```

When deploying:
```
zbctl deploy --insecure orchestration/feel/payer-transaction-request-DFSPID.bpmn
Error: rpc error: code = Unimplemented desc = Method not found: gateway_protocol.Gateway/DeployProcess
```

I remember all the BPMNs deploying correctly in the previous version 0.24.2 (I guess), but we after connecting to a new ES cluster, I am trying to redeploy all the BPMNs but I'm not able. From looks of it, it seems like DeployProcess is missing from the proto but I'm not sure if this is intentional or something is wrong.

**Comment by jwulf** [comment]
Please see this section of the README:


> For pre-1.0.0 versions of Zeebe, install with:

```
npm i -g zbctl@0
```
> For Zeebe versions from 1.0.0-alpha7 and later:

```
npm i -g zbctl
```
