### ISSUE TITLE
Release stable to Docker Hub

### ISSUE THREAD

**Issue by aivinog1** [jwulf/zbctl#13]
Hey!

As I can see [here](https://hub.docker.com/r/sitapati/zbctl/tags) there are no this year versions for a year. I think that problem in tags docker images are pushed if a tag has a `v` prefix. So can you [fix CI](https://github.com/camunda-community-hub/zbctl-via-npm/blob/f318c79bcd514955aca491f08f77e67861d71c11/.github/workflows/release.yml#L7), or push the current stable version, please? :)

**Comment by jwulf** [comment]
8.0.5 is released on NPM and on Docker Hub!

https://hub.docker.com/r/sitapati/zbctl/tags
