### ISSUE TITLE
Include information for debug logging

### ISSUE THREAD

**Issue by nikku** [jwulf/zbctl#27]
### Describe the issue

I'm sure there exists an official way to debug log communcation executed via this utility. Unfortunately I'm not able to learn about it on the [projects readme](https://github.com/camunda-community-hub/zbctl-via-npm), [NPM](https://www.npmjs.com/package/zbctl), nor via the [official documentation](https://docs.camunda.io/docs/apis-tools/cli-client/).

I'm also not able to use known flags (i.e. `--verbose`) in the CLI tool.

### Describe the solution

Both this wrapper package, and the [official documentation](https://docs.camunda.io/docs/apis-tools/cli-client/) clearly outline debug log instructions.

**Comment by jwulf** [comment]
This package is only a wrapper around the utility to provide a way to install it via NPM. If the `zbctl` binary doesn't expose a `--verbose` option, then the place to ask for it is in [the Zeebe repository upstream](https://github.com/camunda/zeebe/issues).

**Comment by nikku** [comment]
Thanks. I raised https://github.com/camunda/zeebe/issues/13084 as an upstream bug report.
