### ISSUE TITLE
ISSUE: Not able to use zbctl status with zeebe multitenancy enabled

### ISSUE THREAD

**Issue by AndersRunningen** [jwulf/zbctl#33]
Description:
When enabling Multitenancy in Zeebe the `zbctl status` command throws error:

```bash
zbctl status
Error: rpc error: code = Unknown desc =
```

Version: 8.4.1 and below

We are installing Zeebe with the Camunda Platform helmchart and running the latest version of the helmchart 9.1.0. When turning off the multitenancy option in the Helmchart, `zbctl status` works fine again. 

```
zbctl status
Cluster size: 3
Partitions count: 3
Replication factor: 3
Gateway version: 8.4.1
Brokers:
  Broker 0 - camunda-platform-zeebe-0.camunda-platform-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 1 : Leader, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Leader, Healthy
  Broker 1 - camunda-platform-zeebe-1.camunda-platform-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 1 : Follower, Healthy
    Partition 2 : Leader, Healthy
    Partition 3 : Follower, Healthy
  Broker 2 - camunda-platform-zeebe-2.camunda-platform-zeebe.camunda.svc:26501
    Version: 8.4.1
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
    Partition 3 : Follower, Healthy
```

Do you have any idea on what is wrong here? Is there some missing functionality around the multitenancy option?

**Comment by jwulf** [comment]
See here: https://docs.camunda.io/docs/self-managed/concepts/multi-tenancy/#unsupported-features
